name: Storybook Test
description: Storybook Test

inputs:
  NEXT_PUBLIC_SUPABASE_URL:
    description: 'NEXT_PUBLIC_SUPABASE_URL'
    required: true
  NEXT_PUBLIC_SUPABASE_ANON_KEY:
    description: 'NEXT_PUBLIC_SUPABASE_ANON_KEY'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Playwright cache
      id: playwright-cache
      uses: actions/cache@v4
      with:
        path: /home/runner/.cache
        key: ${{ runner.os }}-playwright-cache-${{ hashFiles('**/.storybook/test-runner.ts') }}
        restore-keys: ${{ runner.os }}-playwright-cache-
    - name: Install Playwright
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: pnpm exec playwright install --with-deps
    - name: Build storybook
      shell: bash
      run: pnpm build-storybook
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ inputs.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ inputs.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
    - name: Storybook test
      run: pnpm test-storybook:ci
      shell: bash
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ inputs.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ inputs.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
