name: Chromatic
description: Chromatic

inputs:
  G_TOKEN:
    description: 'github token'
    required: true
  CHROMATIC_PROJECT_TOKEN:
    description: 'chromatic token'
    required: true

runs:
  using: "composite"
  steps:
    # - name: Move MSW file
    #   run: mv public/mockServiceWorker.js storybook-static
    #   shell: bash
    - name: Publish to Chromatic
      uses: chromaui/action@v11
      with:
        token: ${{ inputs.G_TOKEN }}
        projectToken: ${{ inputs.CHROMATIC_PROJECT_TOKEN }}
        storybookBuildDir: storybook-static
