import { Provider } from '@/src/components/ui/provider';
import { customErrorMap } from '@/src/configs/zod/zop-setup';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import zod from 'zod';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  zod.setErrorMap(customErrorMap);
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
