name: Migrate Production Database

on:
  push:
    branches:
      - main

jobs:
  migrate-prod-db:
    name: Run Prisma Migrations
    runs-on: ubuntu-latest
    environment: production 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup
        uses: ./.github/actions/setup
      
      - name: Run Database Migration
        run: |
          pnpm prisma migrate deploy || echo "マイグレーションが必要ないか、すでに適用されています"
          exit 0
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }} 